### ISSUE TITLE
Use GP1-7?

### ISSUE THREAD

**Issue by johnwargo** [ControlEverythingCom/NCD1Relay#3]
how do I use GP1 through GP7?  Just turn them on/off to drive voltage to that pin?  I'm assuming yes, but the docs don't say. I want to drive two LEDs using them, I can do that, right?
I see in the readme that I can read the status of the port, but how to I set an output voltage on it?

**Comment by telliottosceola** [comment]
Hi John,

The NCD1Relay library actually sets GP 1-7 as inputs so they can only be used to read external contact closures between the GP and GND.  However we also have NCD2Relay, NCD4Relay, and NCD8Relay libraries.  The NCD8Relay library sets all GPIOs on the MCP23008 to Outputs so you can control those outputs with the turnOnRelay and turnOffRelay functions.  Sounds like NCD8Relay library would work better for your particular application.  You could also use NCD4Relay if you want to use the last 4 GPIOs as inputs.

**Comment by johnwargo** [comment]
Yeah, that's what I did - I installed the NCD4 library and got it to work. Thanks. 

Why not document this? Why did I have to figure this out on my own? Why not update the NCD1 library so you can turn the relay on/of, but then expose other methods like `gpioOn(int port)` or `gpioOff(int port)` so its clear how this works?

**Comment by telliottosceola** [comment]
Honestly I wrote these libraries a long time ago and that functionality just wasn't something I thought of at the time.  We release these libraries to the public for free so we really don't make a whole lot for developing them which limits the amount of time we as a business can invest in updating them for feature additions.

**Comment by johnwargo** [comment]
OK, do you at least want to accept my PR from yesterday? I fixed several typos in the repo's readme.

**Comment by johnwargo** [comment]
I fixed some typos in the docs, are you going to accept them?  Also, if you need someone to help update the docs, let me know, I've written a bunch of books and articles, so I'm available for some contract writing.

**Comment by telliottosceola** [comment]
Hey John,

Sorry for the delay there.  We were closed last week.  I committed your pull requests.  Thank you very much for your contribution.

**Comment by jwargo** [comment]
Thanks. The file had a bunch of errors in it, I just fixed them in a new PR.

**Comment by telliottosceola** [comment]
Thanks John!

**Comment by KrakenBill** [comment]
Does anyone have a drawing available for switching the GP1 to 7?
