### ISSUE TITLE
GPIO Output Voltage

### ISSUE THREAD

**Issue by jwargo** [ControlEverythingCom/NCD1Relay#5]
When you drive the GPIO port hi using `turnOnRelay()`, what output voltage does it send?  The Photon's a 3V device, but you're powering the relay board with 12V, so is that what I'm getting out the GPIO outputs?

**Comment by telliottosceola** [comment]
Hi John,

The GPIO lines are being driven by an MCP23008 GPIO multiplexer.  It is being powered by a 5VDC regulator on the board so it will provide 5VDC on the GPIO lines when driven high.

**Comment by jwargo** [comment]
Thanks
