### ISSUE TITLE
Where do I find these files?  

### ISSUE THREAD

**Issue by xinthose** [ControlEverythingCom/NCD1Relay#8]
https://github.com/ControlEverythingCom/NCD1Relay/blob/279f56f428eabbff1b7c23b4a34a7780c85037fe/firmware/NCD1Relay.h#L1-L3

These files are not in the repository.

**Comment by telliottosceola** [comment]
Hi,

This library was developed for Particle and those library headers are core on Particle.  You can learn more at https://particle.io. If you wish to use this library with Arduino some slight porting would be required but it would not be significant.

**Comment by xinthose** [comment]
OK.  Thank you sir.
